### ISSUE TITLE
https://github.com/pangao1990/vue-pywebview-app

### ISSUE THREAD

**Issue by wanghaisheng** [h7ml/vue-amis-sdk#1]
拖拽式生成的代码  我能和这里整合 吗
有一个文件夹

**Comment by h7ml** [comment]
repo 隐藏权限了吗

**Comment by wanghaisheng** [comment]
好像是没了 

[vue-pywebview-pyinstaller.zip](https://github.com/h7ml/vue-amis-sdk/files/8849620/vue-pywebview-pyinstaller.zip)

**Comment by h7ml** [comment]
你的项目是基于vite esmodule的。amis暂不完全支持esmodule方式，
目前amis是在适配esmodule中，相关issues你可以看看 https://github.com/baidu/amis/search?q=vite&type=issues

**Comment by h7ml** [comment]
![image](https://user-images.githubusercontent.com/55233292/172291764-1e5bf7ab-0c75-4885-a0f5-1dd4f06dfe1b.png)

**Comment by h7ml** [comment]
测试了下 你的项目可以集成进来

**Comment by h7ml** [comment]
![image](https://user-images.githubusercontent.com/55233292/172292591-7c144554-bb82-4a7d-94a1-d9f4b14bb008.png)


> 拖拽式生成的代码 我能和这里整合 吗 有一个文件夹

https://github.com/pangao1990/vue-pywebview-pyinstaller/pull/2

**Comment by wanghaisheng** [comment]
怎么搞怎么搞

**Comment by wanghaisheng** [comment]
我理解是 通过aims的拖拽式 配合这个amis sdk能生成原生vue code 剩下的就 是import或者直接贴代码到template里去

**Comment by h7ml** [comment]
这个只能生成json

**Comment by h7ml** [comment]
生成预览方式你可以看看这里 https://amis-admin-vue.vercel.app/iframe#/

**Comment by wanghaisheng** [comment]
那你说的集成 相当于是aims底层库引入 然后搭配json做展示？

**Comment by h7ml** [comment]
是的

**Comment by h7ml** [comment]
你需要拖拽后生成界面。有两种思路，一种是将生成的json保存到数据库，每次渲染页面前，请求对应的json内容渲染，一种是直接将配置好的json，手动拷贝到页面里。

**Comment by wanghaisheng** [comment]
第一种我好像见过了已经 https://github.com/amisadmin/fastapi_amis_admin这个应该就是
第二种还没有啥子路
你现在这个相当于editor？但我没明白默认的使用方式是咋样的 咋引入到项目中去

**Comment by h7ml** [comment]
> 第一种我好像见过了已经 [https://github.com/amisadmin/fastapi_amis_admin这个应该就是](https://github.com/amisadmin/fastapi_amis_admin%E8%BF%99%E4%B8%AA%E5%BA%94%E8%AF%A5%E5%B0%B1%E6%98%AF) 第二种还没有啥子路 你现在这个相当于editor？但我没明白默认的使用方式是咋样的 咋引入到项目中去

我提的pr给你引入了。

思路参考这个 https://h7ml.gitee.io/amis-editor-demo/#/hello-world

**Comment by wanghaisheng** [comment]
@h7ml  你给的这个 我看不到源码 具体咋操作的
我先用在线编辑器设计界面，得到json
然后使用sdk生成vue 
将得到的vue拷贝到src public文件夹

你之前说一种是直接将配置好的json，手动拷贝到页面里。 我看你的图里也是引用nodemodule里面已经渲染的vue文件

**Comment by wanghaisheng** [comment]
https://github.com/baidu/amis/releases
总算弄得明白了 你这个类似js react的sdk
整个操作方法应该是这样的

**Comment by a009** [comment]
@h7ml @wanghaisheng 请建一个QQ或微信群吧，我也在项目中用了vue+amis，方便大家交流，经验共享。

**Comment by wanghaisheng** [comment]
喊h7ml拉个qq频道

**Comment by a009** [comment]
@h7ml 请建个qq群吧，我们一起探索。
