### ISSUE TITLE
npm i之后项目启动不起来了

### ISSUE THREAD

**Issue by 1129921824** [h7ml/vue-amis-sdk#175]
![image](https://github.com/h7ml/vue-amis-sdk/assets/20693715/a56b16d1-cbb5-4415-8ce8-68f2a71da68f)
麻烦大佬帮忙看一下，
vue2.7.14

**Comment by h7ml** [comment]
看下 https://github.com/h7ml/vue-amis-sdk-examples 对应下版本

**Comment by 1129921824** [comment]
> 看下 https://github.com/h7ml/vue-amis-sdk-examples 对应下版本

为啥我使用2.7.9这个版本，amis的包不会自动下载到我本地呢

**Comment by 1129921824** [comment]
> > 看下 https://github.com/h7ml/vue-amis-sdk-examples 对应下版本
> 
> 为啥我使用2.7.9这个版本，amis的包不会自动下载到我本地呢

你的demo是好使的，我很疑惑

**Comment by h7ml** [comment]
你当前的package管理器是什么呢

**Comment by 1129921824** [comment]
> 

npm

**Comment by 1129921824** [comment]
> 你当前的package管理器是什么呢

npm

**Comment by 1129921824** [comment]
> 你当前的package管理器是什么呢

大佬可以加个好友吗？如果不方便透露您的，我的微信或者qq都是1129921824，(*￣︶￣)

**Comment by 1129921824** [comment]
![image](https://github.com/h7ml/vue-amis-sdk/assets/20693715/52289837-5952-4819-9d15-2b6251151875)

按照demo的做法，把编辑器挂载的根实例上，然后报了上面这个错误

**Comment by 1129921824** [comment]
谢谢大佬的指导，问题已经成功解决

**Comment by 1129921824** [comment]
mark 新版本不能正常显示源码，期待修复
