### ISSUE TITLE
请问大佬能不能出一个自定义组件的版本，我们有些需求需要自定义组件，不知道怎么集成

### ISSUE THREAD

**Issue by Niqian** [h7ml/vue-amis-sdk#24]

**Comment by h7ml** [comment]
项目架构讲下

**Comment by Niqian** [comment]
> 项目架构讲下

我们用的jeecgboot的前端框架，然后在vue-amis-sdk源码基础修改了下依赖到工程里

**Comment by Niqian** [comment]
> > 项目架构讲下
> 
> 我们用的jeecgboot的前端框架，然后在vue-amis-sdk源码基础修改了下依赖到工程里

vue-amis-sdk版本的编译用的node版本是12，项目工程用的node是10（目前使用正常，就是无法显示自定义组件面板，也不知道如何集成自定义组件，官方提供的amis-widget-cli也试过了，组件可以注册成功，但是无法显示）

**Comment by Niqian** [comment]
> > 项目架构讲下
> 
> 我们用的jeecgboot的前端框架，然后在vue-amis-sdk源码基础修改了下依赖到工程里

vue-amis-sdk版本的编译用的node版本是12，项目工程用的node是10（目前使用正常，就是无法显示自定义组件面板，也不知道如何集成自定义组件，官方提供的amis-widget-cli也试过了，组件可以注册成功，但是无法显示）

**Comment by Niqian** [comment]
> > 项目架构讲下
> 
> 我们用的jeecgboot的前端框架，然后在vue-amis-sdk源码基础修改了下依赖到工程里

vue-amis-sdk版本的编译用的node版本是12，项目工程用的node是10（目前使用正常，就是无法显示自定义组件面板，也不知道如何集成自定义组件，官方提供的amis-widget-cli也试过了，组件可以注册成功，但是无法显示）
