### ISSUE TITLE
运行项目报以下错误

### ISSUE THREAD

**Issue by XiaoBaiClassmate** [h7ml/vue-amis-sdk#31]
node:16.16.0

运行 `npm install --legacy-peer-deps` 命令
再运行 `npm run servre`

![`LT45_IQ)8)9$DW%@ }~$ V](https://user-images.githubusercontent.com/39209286/192073908-8cf5a8c5-0283-4e3d-a242-2553e6a01803.png)

如果运行 `npm i` 直接报
![4 G 7}_(J O(Z9Z5U482UA](https://user-images.githubusercontent.com/39209286/192073937-35aa82d3-9e7c-4768-b05d-05d324c8d949.png)

**Comment by h7ml** [comment]
> node:16.16.0
> 
> 运行 `npm install --legacy-peer-deps` 命令 再运行 `npm run servre`
> 
> ![`LT45_IQ)8)9$DW%@ }~$ V](https://user-images.githubusercontent.com/39209286/192073908-8cf5a8c5-0283-4e3d-a242-2553e6a01803.png)
> 
> 如果运行 `npm i` 直接报 ![4 G 7}_(J O(Z9Z5U482UA](https://user-images.githubusercontent.com/39209286/192073937-35aa82d3-9e7c-4768-b05d-05d324c8d949.png)

https://github.com/h7ml/vue-amis-sdk/blob/master/.github/workflows/deploy.yml#L50

 yarn  install

**Comment by XiaoBaiClassmate** [comment]
@h7ml  大佬，安装成功了，但是 npm run serve 报以下错误
![UFJTB{9YG4{$%$DM3RY5OQ6](https://user-images.githubusercontent.com/39209286/192174655-1c199529-b6a8-47ef-8715-09bebae85c8a.png)

**Comment by h7ml** [comment]
> @h7ml 大佬，安装成功了，但是 npm run serve 报以下错误 ![UFJTB{9YG4{$%$DM3RY5OQ6](https://user-images.githubusercontent.com/39209286/192174655-1c199529-b6a8-47ef-8715-09bebae85c8a.png)

大佬，看看环境版本

**Comment by h7ml** [comment]
> @h7ml 大佬，安装成功了，但是 npm run serve 报以下错误 ![UFJTB{9YG4{$%$DM3RY5OQ6](https://user-images.githubusercontent.com/39209286/192174655-1c199529-b6a8-47ef-8715-09bebae85c8a.png)

貌似是amis 组件内部问题，你是编辑中使用了组件还是

**Comment by XiaoBaiClassmate** [comment]
> > @h7ml 大佬，安装成功了，但是 npm run serve 报以下错误 ![UFJTB{9YG4{$%$DM3RY5OQ6](https://user-images.githubusercontent.com/39209286/192174655-1c199529-b6a8-47ef-8715-09bebae85c8a.png)
> 
> 貌似是amis 组件内部问题，你是编辑中使用了组件还是

没有编辑，就是当前项目 拉下来安装，运行查看，发现更不运行不起来

**Comment by h7ml** [comment]
yarn add vue-amis-sdk@2.7.2
