### ISSUE TITLE
更新到2.0.2报Object(...) is not a function

### ISSUE THREAD

**Issue by BruceWa1ne** [h7ml/vue-amis-sdk#65]
![image](https://user-images.githubusercontent.com/52929264/211728181-f9a70cfd-a78a-4dd0-a76e-c25970f553aa.png)
如上图，1.10.2版本正常

**Comment by h7ml** [comment]
amis几？

**Comment by h7ml** [comment]
``yarn add vue-amis-sdk@2.7.2``
